Vagrant.configure(2) do |config|

    config.vm.box = "ubuntu/trusty64"

    #--
    #-- If you've installed the "vagrant-triggers" plugin:
    #-- https://github.com/emyl/vagrant-triggers
    #--
    #config.trigger.after :up, :force => true do
    #    info "Generating Ansible inventory file..."
    #    run  "vag2inv --vm -f --stdout HOSTS-VAGRANT"
    #end

end