sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -t img   .

script:
    - docker run -v $(pwd):/dist  img
    - $(pwd)/vag2inv-linux-x86_64 --help > result

    - echo "==> Validating the test results..."
    - sh -c "[ -s result ]"
